import type { SiteContent } from "@/types/content";

/**
 * Social handles, in one place because the footer and the contact section both
 * need them and a second copy is a second thing to get wrong.
 *
 * `.example` is the IANA-reserved placeholder name, used here for the same
 * reason the phone number and the WhatsApp number are unassigned: these must
 * read unmistakably as stand-ins and must not resolve to some real account that
 * would then be associated with a fictional studio. They are structurally valid
 * links — the pattern is demonstrated — that simply do not lead anywhere.
 */
const HANDLE = "karaneh.example";

const social = {
  instagram: { label: "اینستاگرام", href: `https://instagram.com/${HANDLE}` },
  telegram: { label: "تلگرام", href: `https://t.me/${HANDLE}` },
  pinterest: { label: "پینترست", href: `https://pinterest.com/${HANDLE}` },
};

/**
 * PLACEHOLDER CONTENT.
 *
 * The studio name, contact details and social handles below are stand-ins.
 * Phone and email are deliberately non-functional. Nothing here asserts a fact
 * about a real business; replace the whole object when a client supplies their
 * own details.
 */
export const site: SiteContent = {
  brand: {
    name: "کرانه",
    latin: "KARANEH",
    line: "استودیوی معماری داخلی، برای فضاهای مسکونی و تجاری.",
  },

  /**
   * Document title for the site as a whole. `titleTemplate` wraps whatever a
   * route supplies, so the studio name is written once here rather than being
   * repeated into every page's `<title>` by hand.
   */
  seo: {
    title: "کرانه — استودیوی معماری داخلی",
    titleTemplate: "%s — کرانه",
    description:
      "کرانه استودیوی معماری داخلی است؛ نُه پروژهٔ مسکونی، تجاری و کافه و رستوران، با شرحی از تصمیم‌هایی که هر فضا را ساخته است.",
    /**
     * Generated by `scripts/generate-og.mjs` — a raster, not an SVG, because
     * no social crawler renders an SVG share card. A JPEG rather than a PNG
     * since half the card is now a photograph, which a PNG stores badly.
     */
    ogImage: {
      src: "/media/og-card.jpg",
      alt: "نیمهٔ چپ عکس نشیمنی رو به حیاط در نور بعدازظهر، از پروژه‌های کرانه، نیمهٔ راست نشان کرانه روی زمینهٔ زغالی",
      width: 1200,
      height: 630,
    },
  },

  /**
   * Navigation.
   *
   * Every entry is a real destination. «تماس با ما» deep-links to the contact
   * block on the about page rather than getting a route of its own: the studio
   * has one short story and one set of contact details, which is a page, not
   * two (§19 — do not force five pages if the content needs fewer).
   *
   * Hrefs are written from the site root so the header works on every page —
   * a bare `#contact` resolves against whatever page the header happens to be
   * rendered on, which is nothing at all outside the homepage.
   */
  nav: [
    { label: "پروژه‌ها", href: "/products/" },
    { label: "گالری", href: "/gallery/" },
    { label: "دربارهٔ ما", href: "/about/" },
    { label: "تماس با ما", href: "/about/#contact" },
  ],

  headerCta: { label: "شروع یک پروژه", href: "/about/#contact" },

  contact: {
    city: "تهران",
    phone: "۰۲۱ — ۰۰۰۰ ۰۰۰۰",
    phoneHref: "+982100000000",
    /**
     * WhatsApp number for click-to-chat, in Latin digits with no punctuation —
     * `wa.me` accepts nothing else, and Persian digits are not matched by `\d`
     * (§36.5, the bug that produced empty `tel:` links in Phase 01).
     *
     * Deliberately not a real number, like the phone and email above. `wa.me`
     * answers an unassigned number with "this link is invalid" rather than
     * opening a chat with a stranger, which is the correct behaviour for a
     * placeholder.
     */
    whatsapp: "989000000000",
    email: "studio@karaneh.example",
    /** Secondary inquiry path (§42), for studio-discovery rather than a project question. */
    instagram: { handle: `@${HANDLE}`, href: social.instagram.href },
  },

  social: [social.instagram, social.telegram, social.pinterest],

  /**
   * Empty on purpose, and the footer hides the row while it is.
   *
   * These were «حریم خصوصی» and «شرایط استفاده» pointing at `href="#"` — links
   * that focus like links and jump the reader to the top of the page. The fix
   * is not to write the pages: a privacy policy and terms of use are the one
   * category of content where inventing plausible text is actively harmful,
   * and §44.1 rules out far less consequential fabrications than that.
   *
   * Add real entries here when real policies exist and the row comes back with
   * no change to any component.
   */
  legal: [],

  /** The two column headings in the footer — brand copy, not structure. */
  footer: {
    navHeading: "استودیو",
    contactHeading: "تماس",
  },

  copyright: "© ۱۴۰۵ کرانه — تمام حقوق محفوظ است.",
};
