/**
 * Open Graph card generator.
 *
 * Every image on this site is a hand-authored SVG, and **no social crawler
 * renders an SVG `og:image`** — Facebook, X, LinkedIn and Telegram all ignore
 * it and fall back to no preview at all. So the share card has to be a raster,
 * and it is the one raster in the project.
 *
 * It is written here rather than fetched, generated by a service, or produced
 * with an image library, because the project has exactly three runtime
 * dependencies and adding `sharp` or `resvg` to draw one 1200×630 rectangle is
 * a bad trade. Node's own `zlib` is all a PNG encoder needs.
 *
 * The card is the same art direction as `generate-media.mjs` — a wall plane, a
 * floor plane, and a shaft of light falling from the top-right, which is the RTL
 * reading origin — with the brand mark from `src/app/icon.svg` over it. It
 * carries no type: rendering Persian into a generated raster needs a font
 * pipeline this project does not have, and a Latin-only card for a Persian
 * brand would read worse than a clean mark.
 *
 *   node scripts/generate-og.mjs
 */
import { deflateSync } from "node:zlib";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "public", "media");
mkdirSync(outDir, { recursive: true });

/** Open Graph's expected card size. 1.91:1, which is what every consumer crops to. */
const W = 1200;
const H = 630;

/** Kept in sync with src/app/tokens.css and scripts/generate-media.mjs. */
const ZOGHAL = [0x12, 0x13, 0x14];
const TONE = [0x8c, 0x7a, 0x63];
const NOOR = [0xe8, 0xe8, 0xe6];
const AAJOR = [0x9e, 0x5b, 0x3e];

/* -------------------------------------------------------------------------- */
/*  PNG encoding                                                              */
/* -------------------------------------------------------------------------- */

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body), 0);
  return Buffer.concat([length, body, crc]);
}

/**
 * Truecolour 8-bit PNG from a raw RGB buffer.
 *
 * Every scanline uses filter type 1 (Sub — each byte minus the one three to its
 * left). On a smooth horizontal gradient that leaves a run of near-zeroes, so
 * deflate turns a 2.2 MB raw image into tens of kilobytes. Filter 0 on the same
 * data is several times larger.
 */
function encodePng(width, height, rgb) {
  const stride = width * 3;
  const raw = Buffer.alloc((stride + 1) * height);

  for (let y = 0; y < height; y++) {
    const src = y * stride;
    const dst = y * (stride + 1);
    raw[dst] = 1;
    for (let x = 0; x < stride; x++) {
      const left = x >= 3 ? rgb[src + x - 3] : 0;
      raw[dst + 1 + x] = (rgb[src + x] - left) & 0xff;
    }
  }

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // colour type: truecolour
  // 10–12: compression, filter and interlace methods — all 0, the only values
  // the format defines.

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

/* -------------------------------------------------------------------------- */
/*  The card                                                                  */
/* -------------------------------------------------------------------------- */

const clamp01 = (v) => (v < 0 ? 0 : v > 1 ? 1 : v);
const mix = (a, b, t) => a + (b - a) * t;

/** Smooth 0→1 ramp, used for every soft edge so nothing on the card is aliased. */
function smoothstep(edge0, edge1, x) {
  const t = clamp01((x - edge0) / (edge1 - edge0));
  return t * t * (3 - 2 * t);
}

/** Source-over composite of a straight colour at `alpha` onto `dst`. */
function over(dst, colour, alpha) {
  if (alpha <= 0) return;
  for (let i = 0; i < 3; i++) dst[i] = mix(dst[i], colour[i], alpha);
}

/**
 * Coverage of an axis-aligned rectangle, antialiased across one pixel.
 *
 * The mark only. Its second plane recedes, so its top and bottom edges move
 * with x — which is why this takes four edges rather than a position and a
 * size: the caller passes the edges it has computed for *this* column.
 */
function band(x, y, x0, x1, y0, y1) {
  return (
    smoothstep(x0 - 1, x0 + 1, x) *
    (1 - smoothstep(x1 - 1, x1 + 1, x)) *
    smoothstep(y0 - 1, y0 + 1, y) *
    (1 - smoothstep(y1 - 1, y1 + 1, y))
  );
}

/**
 * A defocused mass: gaussian falloff from a centre.
 *
 * Deliberately *not* a wide smoothstep, which is what the first version of this
 * card used. A smoothstep reaches exactly zero at a finite radius, and at 8 bits
 * per channel that last contour is a visible ring — this card had one arcing
 * from the top-left corner down to the right edge, from a highlight whose
 * falloff happened to end on screen. A gaussian only ever approaches zero, so
 * there is no radius for the eye to find.
 */
function glow(x, y, cx, cy, sigma) {
  const d2 = (x - cx) ** 2 + (y - cy) ** 2;
  return Math.exp(-d2 / (2 * sigma * sigma));
}

/**
 * Ordered dither, not film grain.
 *
 * A wide gradient at 8 bits per channel bands: a 0.14-alpha white spread over
 * 300px gets about 36 levels, so each one occupies ten pixels and the eye reads
 * the contours as edges. Something has to break that up.
 *
 * The studies use random film grain, and measured here that costs 401 KB at the
 * faintest visible amplitude and 541 KB at theirs, against 95 KB smooth —
 * per-pixel noise is precisely what deflate cannot compress. A 4×4 Bayer matrix
 * does the same job for a fraction of that, because it repeats and deflate is
 * very good at things that repeat.
 */
const BAYER = [
  [0, 8, 2, 10],
  [12, 4, 14, 6],
  [3, 11, 1, 9],
  [15, 7, 13, 5],
];

const rgb = Buffer.alloc(W * H * 3);
const px = [0, 0, 0];

/** Where the wall plane meets the floor plane. */
const FLOOR_Y = 424;

// The brand mark, from src/app/icon.svg: a 32-unit box scaled up and centred
// slightly left of middle, so the shaft of light passes behind it rather than
// through it. Every consumer crops this card differently, so it stays near
// enough to the centre to survive a square crop.
const MARK = { size: 320, cx: 560, cy: 300 };
const scale = MARK.size / 32;
const originX = MARK.cx - MARK.size / 2;
const originY = MARK.cy - MARK.size / 2;
const markX = (u) => originX + u * scale;
const markY = (v) => originY + v * scale;

for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    px[0] = ZOGHAL[0];
    px[1] = ZOGHAL[1];
    px[2] = ZOGHAL[2];

    // 1 — the two planes. The floor takes more of the tone, which is what
    // separates it from the wall without drawing a line to say so.
    const onFloor = smoothstep(FLOOR_Y - 1, FLOOR_Y + 1, y);
    over(px, TONE, mix(0.17, 0.36, onFloor));

    // 2 — the tonal fall, top-right to bottom-left.
    const fall = clamp01((x / W) * 0.55 + (1 - y / H) * 0.45);
    over(px, TONE, mix(0.02, 0.3, fall));

    // 3 — the shaft. Its centre walks left as it descends and it widens as it
    // goes, which is what a real one does; a constant-width diagonal reads as
    // a painted stripe.
    const shaftX = 980 + (y / H) * (300 - 980);
    const shaftW = 150 + (y / H) * 170;
    over(px, [255, 255, 255], 0.17 * Math.exp(-(((x - shaftX) / shaftW) ** 2)));
    over(px, [0, 0, 0], 0.22 * glow(x, y, 90, 620, 300));

    // 4 — the seam where the planes meet: a hairline, not an edge.
    over(px, [0, 0, 0], 0.26 * Math.exp(-(((y - FLOOR_Y) / 2.4) ** 2)));

    // 5 — the mark, the one crisp thing on the card. Its second plane recedes,
    // so its edges are computed for this column rather than fixed.
    const mu = (x - originX) / scale;
    over(px, NOOR, band(x, y, markX(5), markX(15), markY(6), markY(26)) * 0.95);
    over(
      px,
      AAJOR,
      band(x, y, markX(18), markX(27), markY(9 - (mu - 18) / 3), markY(23 + (mu - 18) / 3)),
    );

    // 4 — the light source at 78% / 18%, and the vignette that closes it.
    // Both smooth for the same reason as the masses above: the earlier version
    // ramped white to 52% and then black from 52%, and that kink in the slope
    // is another contour the eye can pick out.
    const u = x / W - 0.78;
    const v = y / H - 0.18;
    const t = Math.hypot(u, v) / 0.88;
    over(px, [255, 255, 255], 0.18 * Math.exp(-((t / 0.42) ** 2)));
    over(px, [0, 0, 0], 0.22 * smoothstep(0.45, 1.2, t));

    const d = (BAYER[y & 3][x & 3] / 16 - 0.5) * 1.6;

    const o = (y * W + x) * 3;
    rgb[o] = clamp01((px[0] + d) / 255) * 255;
    rgb[o + 1] = clamp01((px[1] + d) / 255) * 255;
    rgb[o + 2] = clamp01((px[2] + d) / 255) * 255;
  }
}

const file = join(outDir, "og-card.png");
const png = encodePng(W, H, rgb);
writeFileSync(file, png);
console.log(`generated og-card.png  ${W}×${H}  ${(png.length / 1024).toFixed(0)} KB → public/media/`);
